version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: pnpm run dev
    ports:
      - '${APP_PORT}:3000'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
